name: devskim
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 37 7 * * 3
permissions:
  actions: read
  contents: read
  security-events: write
jobs:
  devskim:
    name: devskim
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: analysis
        uses: microsoft/DevSkim-Action@4b5047945a44163b94642a1cecc0d93a3f428cc6
      - name: upload
        uses: github/codeql-action/upload-sarif@6bb031afdd8eb862ea3fc1848194185e076637e5
        with:
          sarif_file: devskim-results.sarif
